language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - rbx-2
  - ruby-head
  - jruby
  - jruby-head

notifications:
  email:
    recipients:
      - goesmeira@gmail.com

script: bundle exec rspec spec
